apiVersion: v2
name: hanko
description: A Helm chart for Hanko Authentication Service
type: application
appVersion: "v1.0.0"
version: 0.1.1
home: https://www.hanko.io
sources:
  - https://github.com/teamhanko/hanko
keywords:
  - authentication
  - identity
  - oidc
  - oauth
  - passkey
  - webauthn
  - iam
maintainers:
  - name: hanko
    email: support@hanko.io
    url: https://www.hanko.io
