{{- $secretName := printf "%s-config" (include "hanko.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "hanko.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- include "hanko.config" . | nindent 4 }}
