apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hanko.fullname" . }}
  labels:
    {{- include "hanko.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hanko.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hanko.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hanko.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.migration.enabled }}
      initContainers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /hanko
            - --config
            - /etc/config/config.yaml
            - migrate
            - up
          env:
            {{- if .Values.postgresql.enabled }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: password
            {{- else if .Values.config.database.passwordSecret }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.database.passwordSecret }}
                  key: password
            {{- end }}
            {{- if or .Values.config.session.secretSecretName .Values.config.secrets.secretsSecretName }}
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.session.secretSecretName | default .Values.config.secrets.secretsSecretName }}
                  key: secret
            {{- end }}
            {{- if .Values.config.secrets.secretsSecretName }}
            - name: SECRETS_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.secrets.secretsSecretName }}
                  key: keys
            {{- end }}
            {{- if .Values.config.emailDelivery.smtp.passwordSecret }}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.emailDelivery.smtp.passwordSecret }}
                  key: password
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.migration.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migration.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migration.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migration.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- else if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /hanko
            - serve
            - --config
            - /etc/config/config.yaml
            - all
          ports:
            - name: http-public
              containerPort: {{ .Values.config.server.public.port }}
              protocol: TCP
            - name: http-admin
              containerPort: {{ .Values.config.server.admin.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health/ready
              port: http-public
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http-public
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.postgresql.enabled }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: password
            {{- else if .Values.config.database.passwordSecret }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.database.passwordSecret }}
                  key: password
            {{- end }}
            {{- if or .Values.config.session.secretSecretName .Values.config.secrets.secretsSecretName }}
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.session.secretSecretName | default .Values.config.secrets.secretsSecretName }}
                  key: secret
            {{- end }}
            {{- if .Values.config.secrets.secretsSecretName }}
            - name: SECRETS_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.secrets.secretsSecretName }}
                  key: keys
            {{- end }}
            {{- if .Values.config.emailDelivery.smtp.passwordSecret }}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.emailDelivery.smtp.passwordSecret }}
                  key: password
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        - name: config
          secret:
            secretName: {{ printf "%s-config" (include "hanko.fullname" .) }}
        {{- toYaml . | nindent 8 }}
      {{- else }}
      volumes:
        - name: config
          secret:
            secretName: {{ printf "%s-config" (include "hanko.fullname" .) }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
